### ISSUE TITLE
Will there be an update? (Yes)

### ISSUE THREAD

**Issue by KoRn0509** [finch-harold/iRedAdmin-Pro-SQL#2]
Update pls 5.5
https://docs.iredmail.org/iredadmin-pro.releases.html

**Comment by SantaFox** [comment]
+1

We wish to buy you a coffee :)

**Comment by Digital-Daz** [comment]
Absolutely awesome stuff but yes there is a 5.5 release.

**Comment by marcus-alicia** [comment]
@KoRn0509 @PBXForums  @SantaFox 
was a bit dead recently. Also working on another project. but I'll update to 5.6 in a few days or so!! <3

**Comment by marcus-alicia** [comment]
> +1
> 
> We wish to buy you a coffee :)

`41kyWeeoVdK4quzQ4M9ikVGs6tCQCLfdx8jLExTNsAu2SF1QAyDqRdjfGM6EL8L9NpXwt89HJeAoGf1aoArk7nDr4AMMV4T` - Monero

All I can offer sadly, since any real donation link might get me in trouble.

**Comment by marcus-alicia** [comment]
https://discord.gg/96kh6n5EMB

**Comment by marcus-alicia** [comment]
Updated

**Comment by marekm72** [comment]
5.6 is released

**Comment by KoRn0509** [comment]
update pls [5.7.1](https://forum.iredmail.org/topic20765.html)
